### ISSUE TITLE
Which node version is used in this project?

### ISSUE THREAD

**Issue by stanma** [lazyexpert/node-cms#1]
We came to the issue of judging your work because of unknown version of nodejs used in your project. Please specify one to make it clear. It would be also great if you could specify the OS you used to run application.

Thank you.

**Comment by lazyexpert** [comment]
Sure, node v0.10.38, OS ubuntu 14.04 LTS.

**Comment by stanma** [comment]
Yes, getting this:

root@vagrant-ubuntu-trusty-32:/vagrant# nodejs app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
: No such file or directoryANIFEST-000980
    at /vagrant/node_modules/admin/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:118:34

root@vagrant-ubuntu-trusty-32:/vagrant# nodejs -v
v0.10.38

root@vagrant-ubuntu-trusty-32:/vagrant# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

Do you use 64bits Ubuntu?

**Comment by lazyexpert** [comment]
No, its 32bits. Still playing around vargant..

**Comment by stanma** [comment]
So you don't get such a problem on your localbox? Or you're running in vagrant too? I didn't understand.

**Comment by lazyexpert** [comment]
I dont have such problems on my machine. And i'm trying to figure out how to set it to vargant, to help you in any way... My local copy starts without any problems

**Comment by lazyexpert** [comment]
The error you recieve is pointing at the Level module https://www.npmjs.com/package/level, if this can help..

**Comment by lazyexpert** [comment]
i recieved the same error when copied the repository, not launching it from local, give me 10 minutes, ill find differences

**Comment by lazyexpert** [comment]
I've figured: the problem was in Level's db manifest file.. My bad, i didn't clone it to the repository, assuming it's one of my local db files... I've pushed this file to the github repository.

**Comment by stanma** [comment]
Great. At least we will be able to check your work. I have to inform you that you will get penalty for this unfortunately :(

**Comment by lazyexpert** [comment]
Well, pitty.

**Comment by stanma** [comment]
Yes. Btw, I'm still getting the same:

root@vagrant-ubuntu-trusty-32:/vagrant# nodejs app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
: No such file or directoryANIFEST-000008
    at /vagrant/node_modules/admin/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:118:34

Something is still wrong even with the latest version of source from git

**Comment by lazyexpert** [comment]
Can you please check manually, do you have the file: "/db/MANIFEST-000008"?

**Comment by stanma** [comment]
yes, checked of course. It is there.

**Comment by lazyexpert** [comment]
I believe, this will be a good lesson for me. The only way i see to solve this problem is to refactor my code, throwing this "level db" away. 

Actually, i used this for 2 simple things:
storing all MySQL settings
storing admin login/pass

Next time, ill use simple file storage read/write stream... Sorry for all this inconveniece.
Hope to see you next time.

**Comment by lazyexpert** [comment]
If not late. Try just delete db folder. Its auto-generated. And than run node app.js, and localhost:3000/install in browser.
